#!/usr/bin/env bash
# Registers a "Thawdrop Share" entry in the Nautilus (GNOME Files) right-click
# "Scripts" submenu for any selected file.
#
# Usage: ./install.sh /path/to/Thawdrop.AppImage
set -euo pipefail

APP_PATH="${1:-}"
if [[ -z "$APP_PATH" ]]; then
  echo "Usage: $0 /path/to/Thawdrop (AppImage or install path)" >&2
  exit 1
fi
if [[ ! -x "$APP_PATH" ]]; then
  echo "Not found or not executable: $APP_PATH" >&2
  exit 1
fi

SCRIPTS_DIR="$HOME/.local/share/nautilus/scripts"
mkdir -p "$SCRIPTS_DIR"

SCRIPT_PATH="$SCRIPTS_DIR/Thawdrop Share"
cat > "$SCRIPT_PATH" <<EOF
#!/usr/bin/env bash
# Auto-generated by thawdrop/scripts/linux/install.sh
while IFS= read -r f; do
  "$APP_PATH" --share "\$f" &
done <<< "\$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
EOF
chmod +x "$SCRIPT_PATH"

echo "Installed. Right-click a file in Nautilus → Scripts → 'Thawdrop Share'."
echo "(Other file managers: Nemo/Caja use the same scripts folder convention;"
echo " Dolphin/Thunar need a .desktop service menu instead — ask if you need that.)"
echo "To remove: rm \"$SCRIPT_PATH\""
